language: node_js

node_js:
  - '4'
  - '6'

sudo: false

notifications:
  email:
    smcarthur@mozilla.com
  irc:
    channels:
      - 'irc.mozilla.org#fxa-bots'
    use_notice: false
    skip_join: false
